name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build site
      run: |
        sed -i "s|{{APIKEY}}|$APIKEY|g" index.html

    - name: Pull Docker Image
      run: docker pull --insecure ghcr.io/actions/jekyll-build-pages:v1.0.7
